name: Deploy to EC2 Windows Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Windows Server
        run: |
          $ErrorActionPreference = 'Stop'

          # Convert password to secure string
          $password = ConvertTo-SecureString $env:WINDOWS_PASSWORD -AsPlainText -Force

          # Create credential object
          $cred = New-Object System.Management.Automation.PSCredential("administrator", $password)

          # Establish a new PSSession
          $session = New-PSSession -ComputerName 44.216.5.15 -Credential $cred -Authentication Default -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck)

          # Check if session was created successfully
          if (-not $session) {
              Write-Error "Failed to create PSSession."
              exit 1
          }

          # Execute commands on remote server with detailed logging
          Invoke-Command -Session $session -ScriptBlock {
            try {
              cd C:\inetpub\wwwroot\core-back.deliver.ar
              Write-Output "Navigated to the target directory."

              if (Test-Path -Path .git) {
                Write-Output "Git repository found. Pulling latest changes."
                git pull origin develop
              } else {
                Write-Output "Git repository not found. Cloning repository."
                git clone https://github.com/gerfalasco/xwallet_backend .
                cd xwallet_backend
                git checkout develop
              }
            } catch {
              Write-Error "An error occurred during the git operations: $_"
              exit 1
            }
          } -ErrorAction Stop

          # Remove the PSSession
          Remove-PSSession -Session $session
        env:
          WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}




