name: Deploy to EC2 Windows Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Windows Server
        run: |
          $password = ConvertTo-SecureString $env:WINDOWS_PASSWORD -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential("administrator", $password)
          $session = New-PSSession -ComputerName 44.216.5.15 -Credential $cred -Authentication Default -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck)
          
          Invoke-Command -Session $session -ScriptBlock {
            cd C:\inetpub\wwwroot\core-back.deliver.ar
            if (Test-Path -Path .git) {
              git pull origin develop
            } else {
              git clone https://github.com/gerfalasco/xwallet_backend .
              git checkout develop
            }
          }
        env:
          WINDOWS_PASSWORD: ${{ secrets.WINDOWS_PASSWORD }}




