name: Deploy to EC2 Windows Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install WinRM
        run: |
          Install-Module -Name PSWSMan -Force -SkipPublisherCheck
          Install-Module -Name WinRM -Force -SkipPublisherCheck
          Install-Module -Name Posh-SSH -Force -SkipPublisherCheck

      - name: Configure WinRM
        run: |
          $secpasswd = ConvertTo-SecureString "${{ secrets.WINDOWS_PASSWORD }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential ("administrator", $secpasswd)
          Set-WSManQuickConfig -Force
          New-PSSession -ComputerName 44.216.5.15 -Credential $creds -Authentication Default -UseSSL -SessionOption (New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck)
          $session = New-PSSession -ComputerName 44.216.5.15 -Credential $creds -Authentication CredSSP -UseSSL

      - name: Deploy to Windows Server
        run: |
          Invoke-Command -Session $session -ScriptBlock {
            cd C:\inetpub\wwwroot\core-back.deliver.ar
            if (Test-Path -Path .git) {
              git pull origin develop
            } else {
              git clone https://github.com/gerfalasco/xwallet_backend .
              git checkout develop
            }
          }



