name: Deploy to EC2

on:
  push:
    branches:
      - develop  # Cambiado a tu rama principal (develop)

jobs:
  deploy:
    runs-on: windows-latest  # Se ejecutará en una máquina Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH for Windows
      run: |
          choco install openssh -y
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          RefreshEnv  # Actualiza las variables de entorno después de instalar SSH

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Verify SSH connection
      run: |
         ssh -o StrictHostKeyChecking=no administrator@44.216.5.15 "echo 'SSH connection successful'"
      continue-on-error: true

    - name: Ensure Git is installed on EC2
      run: |
         ssh -o StrictHostKeyChecking=no administrator@44.216.5.15 "git --version || choco install git -y"
      continue-on-error: true

    - name: Verify initial state of the repository
      run: |
         ssh -o StrictHostKeyChecking=no administrator@44.216.5.15 "
           cd C:/inetpub/wwwroot/core-back.deliver.ar && \
           git status && \
           git remote -v
         "
      continue-on-error: true

    - name: SSH into EC2 instance and perform git pull
      run: |
         ssh -o StrictHostKeyChecking=no administrator@44.216.5.15 "
           cd C:/inetpub/wwwroot/core-back.deliver.ar && \
           git config --global --add safe.directory C:/inetpub/wwwroot/core-back.deliver.ar && \
           echo 'Fetching latest changes' && \
           git fetch origin develop && \
           echo 'Resetting to the latest changes' && \
           git reset --hard origin/develop && \
           git log -1
         "
      continue-on-error: true

    - name: Check contents of the directory after pull
      run: |
         ssh -o StrictHostKeyChecking=no administrator@44.216.5.15 "dir C:/inetpub/wwwroot/core-back.deliver.ar"
      continue-on-error: true

    - name: Verify final state of the repository
      run: |
         ssh -o StrictHostKeyChecking=no administrator@44.216.5.15 "
           cd C:/inetpub/wwwroot/core-back.deliver.ar && \
           git status
         "
      continue-on-error: true
