name: Deploy to EC2 Windows Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Windows Server
        uses: mikeslinn/github-action-windows-winrm@v0.1.1
        with:
          hostname: 44.216.5.15  # IP pública de tu instancia EC2
          username: administrator  # Nombre de usuario para acceder a la instancia EC2
          password: ${{ secrets.WINDOWS_PASSWORD }}  # Contraseña de usuario, almacenada en secretos de GitHub
          command: |
            cd C:\inetpub\wwwroot\core-back.deliver.ar
            if (Test-Path -Path .git) {
              git pull origin develop
            } else {
              git clone https://github.com/gerfalasco/xwallet_backend .
              git checkout develop

