name: Deploy to EC2

on:
  push:
    branches:
      - develop  # Cambiado a tu rama principal (develop)

jobs:
  deploy:
    runs-on: windows-latest  # Se ejecutará en una máquina Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH for Windows
      run: |
        choco install openssh -y
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        RefreshEnv  # Actualiza las variables de entorno después de instalar SSH

    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create SSH config file
      run: |
        echo "Host ec2-instance" > $HOME/.ssh/config
        echo "  HostName 44.216.5.15" >> $HOME/.ssh/config
        echo "  User administrator" >> $HOME/.ssh/config
        echo "  StrictHostKeyChecking no" >> $HOME/.ssh/config
        echo "  IdentityFile $HOME/.ssh/id_rsa" >> $HOME/.ssh/config

    - name: Verify SSH connection
      run: |
        echo "Starting SSH connection verification"
        ssh -v ec2-instance "echo 'SSH connection successful'"
      continue-on-error: true

    - name: Ensure Git is installed on EC2
      run: |
        echo "Checking if Git is installed"
        ssh -v ec2-instance "git --version || choco install git -y"
      continue-on-error: true

    - name: Verify initial state of the repository
      run: |
        echo "Verifying initial state of the repository"
        ssh -v ec2-instance "
          cd C:/inetpub/wwwroot/core-back.deliver.ar && \
          git status && \
          git remote -v
        "
      continue-on-error: true

    - name: SSH into EC2 instance and perform git pull
      run: |
        echo "Performing git pull"
        ssh -v ec2-instance "
          cd C:/inetpub/wwwroot/core-back.deliver.ar && \
          git config --global --add safe.directory C:/inetpub/wwwroot/core-back.deliver.ar && \
          git fetch origin develop && \
          git reset --hard origin/develop && \
          git log -1
        "
      continue-on-error: true

    - name: Check contents of the directory after pull
      run: |
        echo "Checking contents of the directory after pull"
        ssh -v ec2-instance "dir C:/inetpub/wwwroot/core-back.deliver.ar"
      continue-on-error: true

    - name: Verify final state of the repository
      run: |
        echo "Verifying final state of the repository"
        ssh -v ec2-instance "
          cd C:/inetpub/wwwroot/core-back.deliver.ar && \
          git status
        "
      continue-on-error: true
